### ISSUE TITLE
devices found but no entities

### ISSUE THREAD

**Issue by noizecrypto** [Ekman/home-assistant-hiveos#5]
all devices are found but there was not entities created except from power switch.

the power switch button always shows off and once i manually trigger it it auto switch to off. The rig is online and hashing.

and thanks for doing the work integrating this to home assistant ;)

**Comment by Ekman** [comment]
So happy that people are using the integration. 🙂 

Currently, the integration only has one entity, which will turn the miner on and off. It will not power the miner on and off, it will just start and stop the miner. It may take some time, give it ~1 minute for the status to show properly on the switch. It's not perfect but I it works and few people will make decisions to mine on a minute-by-minute basis.

Additionally, there's a service called `hiveos.worker_shutdown` that will shut down (i.e. the power) of the miner.

Personally, I take decisions to mine or not based on electricity price, solar production, etc. I combine the service with a smart plug to gracefully shut down the miner and ultimately cut the power to it.

What more entities would you like to see in the integration?

_Note! Starting the miner right now is wonky since there seems to be a bug in HiveOS where starting a miner does not apply overclock settings. Only starting the miner directly from the boot will, so starting the miner will actually reboot it._

**Comment by noizecrypto** [comment]
The basic Informations like current: watt, hash, temp and uptime would be awesome :)
